### PR TITLE
Upgrade to jdk-1.8.0-181 to satisfy Presto's requirement

### PR DESCRIPTION
**Pull request by xerial**

### CODE REVIEW

**Comment by yyuu** [comment]
We might need to upgrade runtime JDK for the presto upgrade :eyes:

**Comment by xerial** [comment]
@yyuu Yes. We should do it, when using this Presto version.

**Comment by yyuu** [comment]
Packaging JDK as a part of our presto's package could be the way. Will look into it, once we finish current project....

**Comment by xerial** [comment]
Merged to fix the master branch build on CircleCI

**Pull request merged**
